### ISSUE TITLE
Some installation problems and solutions

### ISSUE THREAD

**Issue by nadezdaalexandrovna** [ctapweb/ctap#2]
To install the system on your own server, you would need to compile the project with Maven. I would say the easiest way to do it is to install both GWT and Maven in Eclipse. Import the project into your Eclipse workspace. Then try to run the project in GWT's super dev mode. If it runs successfully, then you can be sure that the project would build correctly in your system. Then you can run GWT's compile command to build the project. Make a JAR archive out of the whole src/main/webapp folder. You are then good to go with any web container you have installed on your server. This is the general process.

About the database setup, the current code uses PostgreSQL. If you also have PostgreSQL installed on the server, you can create a user and database and enter the database information in the properties file (com.ctapweb.web.server.ServerProperties.java). Also setup your database initialization password and administrator email in this file. Then go to   http://yourserver.com:8080/ctapweb/#initdb and use the password to initialize your database, which basically creates all the tables needed for the system. If everything works correctly, you will then be able to signup new users and log into the system. If you don't use PostgreSQL, you can modify the file DBConnectionManager.java to load your own database driver. But the other settings are the same.

I would suggest you first try to run it locally in your Eclipse environment to figure out how the system works before you actually deploy it onto a production server.

Besides, we are working on a new (simplified) version of the system and may have it available in one or two months. The new version uses simple REST service API so would be much easier to use with any client technology that supports HTTP protocol. So no GWT setup will be necessary.

The ctap features are in a sibling project to the ctap-web project. If you have both projects downloaded, all you need to do is to login the system installed locally with the admin account that you set up in the configuration file. Then you will see the "Admin" menu once you login. Go to "Analysis Engine" and click on "Import AE". The system will automatically import all analysis engines from the ctap-feature project.

- Could you please tell me where the configuration file is? Where do I have to set up the admin account?

It's in the java file src/main/java/com/ctapweb/web/server/ServerProperties.java, in which you can set the ADMINEMAIL to an email that you want to specify as the administrator. Then register a new user with that email address. After logging in with this user, you will see the admin menu items.

- I succeeded in logging in as admin, but I can't import AE. When I press the "Import AE" button, an error 500 message appears.

Could you check the web container logs and see what exceptions are actually thrown by the 500 errors?
I am wondering how you build the java projects. Did you try to run the project in Eclipse or in a deployed web container? I would suggest first making sure it runs in the Eclipse environment before deploying the WAR file to any web container because it would be easier for you to see where the problems are. If you run the ctap-web in Eclipse, it would look for the ctap-feature project automatically and build the ctap-feature project and include the built jar file in the webapp/lib folder. If you don't see the ctap-feature.jar in the lib folder, it means that it has been built and added as a dependent library properly. In such cases, you might get a 500 error when you try to import the analysis engines and if you check the web container log, you would see something like "File not found or could not be located". 

- We deployed CTAP in Tomcat in a docker. We did not run it in Eclipse.
 I checked the WEB-INF/lib folder and found the ctap-feature-1.0.0-SNAPSHOT.jar that weighs 43M.
 In the Tomcat logs I found the following error:

 Caused by: java.lang.IllegalArgumentException: Parameter 'directory' is not a directory: file:/usr/local/tomcat/webapps/ctapWebApp/WEB-INF/lib/ctap-feature-1$
        at org.apache.commons.io.FileUtils.validateListFilesParameters(FileUtils.java:536)
        at org.apache.commons.io.FileUtils.listFiles(FileUtils.java:512)
        at org.apache.commons.io.FileUtils.iterateFiles(FileUtils.java:620)
        at com.ctapweb.web.server.admin.ImportAE.importAEDescriptorFolder(ImportAE.java:169)
        at com.ctapweb.web.server.admin.ImportAE.importFeatureUIMADescriptors(ImportAE.java:62)
        at com.ctapweb.web.server.admin.AdminServiceImpl.importAE(AdminServiceImpl.java:933)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.gwt.user.server.rpc.RPC.invokeAndEncodeResponse(RPC.java:587)
        ... 31 more

I am not really sure what is going on with this exception. It seems like that ImportAE.java could not find the analysis engine descriptors (the xml files) that are supposed to be in the classpath. Could you please check if the ctap-feature-1.0.0-SNAPSHOT.jar contains folders called descriptor/annotator and descriptor/featureAE. If not, maybe you need to add them as source folders in the ctap-web project or the ctap-feature project so that when you build the projects, the descriptor folder is included in the library and final jar.

**Comment by nadezdaalexandrovna** [comment]
We have tried to fix this by unpacking the ctap-feature-1.0.0-SNAPSHOT.jar. After this, there is now a new error, which is unfortunately very unclear. Do you have an idea what might be going wrong there?

[nullpointer.txt](https://github.com/ctapweb/ctap/files/1450208/nullpointer.txt)

**Comment by nadezdaalexandrovna** [comment]
Installation instructions:
- Download and install Eclipse Neon (GWT plugin only support up to Neon)
	https://www.eclipse.org/downloads/packages/release/neon/3

- In Eclipse, install GWT Plugin and make sure it runs correctly.
  - the plugin update site:
    https://developers.google.com/eclipse/docs/getting_started
	 https://dl.google.com/eclipse/plugin/4.6

- Clone the CTAP project from Github
	- The parent project: https://github.com/ctapweb/ctap.git
	- The ctap-web project: https://github.com/ctapweb/ctap-web.git
	- The ctap-feature project:
	  https://github.com/ctapweb/ctap-feature.git
	- Remember to put the ctap-web and ctap-feature project inside of
	  the ctap (parent) project

- Import the projects into Eclipse

- In Eclipse, setup the ctap-web project to use GWT. Otherwise you
  will not see the Run/Super dev mode menu item.
  - Right click on the project name and in the properties window, go
	 to the Google configuration and select use GWT with the default
	 environment.

- Remove the classpath /ctap-feature/src/test/java if GWT complains
  about not being able to find the classpath.

- Create a user and database in Postgresql and keep note of the DB
  info.
  - Login as root user of Postgresql: psql -U postgres
  - Create user:
  		CREATE ROLE ctap_test WITH PASSWORD 'ctap_test' LOGIN;
		CREATE DATABASE ctap_test WITH OWNER ctap_test;
  - Log into Postgresql with the new user and make sure it is
	 correctly setup.

- Edit the java file in ctap-web's package:
	- com.ctapweb.web.server.ServerProperties
	- add the DB credentials
	- set the INITDBPASSWD, you will need that to initialize your DB
	- set the ADMINEMAIL, for example, "admin@example.com", you will
	  register this user and when you log in with it, you will see the
	  admin menu items.

- Run the project in Super Dev Mode and open the generated URL in a
  browser. The project would compile.

- Go to the URL http://127.0.0.1:8888/index.html#initdb and enter the
  INITDBPASSWD you set up earlier to create the DB tables.

- Go to the URL http://127.0.0.1:8888/index.html#login to create the
  admin user and log in.

- Go to the Analysis Engine menu and click on "Import AE" to import
  all analysis engines.

- Try the system. If the analysis complains about not having enough
  memory, increase the memory in the Run Configuration.

- Set log level to TRACE if you want to see more what is going on.

# for deploying on external web containers like Tomcat
- Link the "resouces" folder from the ctap-feature project as a source
  folder of ctap-web.

- Compile the GWT project by going to Google/GWT Compile Project.

- Run the Maven package goal by clicking Run/Run as.../Build and enter
  "package" as the goal. You will then get a WAR file in the target
  folder in your project root. 

- Deploy the WAR file in your web container.

**Comment by nadezdaalexandrovna** [comment]
Video tutorial:
https://www.youtube.com/watch?v=_rb-eRhsFH0&list=PLbyPrDZ9AZI9auLKdQMs7ifiqskEwq_k9

**Comment by kreetrapper** [comment]
We have figured out what needs to be added to the pom file to make maven able to build the whole project properly without needing to build it in Eclipse by hand. Could you please merge our pull request in ctap-web (https://github.com/ctapweb/ctap-web/pull/5) with these changes into your repo?
